DROP TABLE IF EXISTS tbUczniowie;
DROP TABLE IF EXISTS tbklasy;

CREATE TABLE tbUczniowie
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	imie TEXT,
	nazwisko TEXT,
	plec INTEGER,
	id_klasa INTEGER,
	egzHum NUMERIC NOT NULL DEFAULT 0,
	egzMat NUMERIC NOT NULL DEFAULT 0,
	egzJez NUMERIC NOT NULL DEFAULT 0,
	FOREIGN KEY (id_klasa) REFERENCES tbKlasy(id)
);

CREATE TABLE tbKlasy
(
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		klasa TEXT,
		rokNaboru INTEGER,
		rokMatury INTEGER
);